name: Deploy to Server

on:
  workflow_dispatch:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy to Server
        uses: burnett01/rsync-deployments@6.0.0
        with:
          remote_host: ${{ secrets.REMOTE_SERVER_HOST }}
          remote_user: ${{ secrets.REMOTE_SERVER_USERNAME }}
          remote_key: ${{ secrets.REMOTE_SERVER_KEY }}
          remote_port: ${{ secrets.REMOTE_SERVER_PORT }}
          remote_key_pass: ${{ secrets.REMOTE_SERVER_KEY_PASS }}
          switches: -avzr --delete
          path: ./*
          remote_path: ${{ secrets.REMOTE_SERVER_PATH }}
